name: publish

on: push

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: mkdir -p res
      - run: chmod 0777 ./res
      - run: ls > res/tree.txt
      - run: npm publish
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cache
          path: res
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
